require("dotenv").config();
const express=require("express"),mysql=require("mysql2/promise"),cors=require("cors"),argon2=require("argon2"),jwt=require("jsonwebtoken");
const app=express(),PORT=Number(process.env.PORT)||3000;
if(!process.env.JWT_SECRET){console.error("JWT_SECRET manque dans .env");process.exit(1)}
const db=mysql.createPool({host:process.env.DB_HOST||"localhost",port:Number(process.env.DB_PORT)||3306,user:process.env.DB_USER||"root",password:process.env.DB_PASSWORD||"",database:process.env.DB_NAME||"dtjob",waitForConnections:true,connectionLimit:10});
app.use(cors({origin:process.env.FRONTEND_ORIGIN||"http://127.0.0.1:5500"}));app.use(express.json());
const makeToken=u=>jwt.sign({id:u.id,role:u.role},process.env.JWT_SECRET,{expiresIn:"2h"});
function auth(req,res,next){const h=req.headers.authorization;if(!h||!h.startsWith("Bearer "))return res.status(401).json({error:"Connexion nécessaire."});try{req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:"Jeton invalide ou expiré."})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({error:"Accès réservé à un administrateur."});next()}
const safe=u=>({id:u.id,first_name:u.first_name,last_name:u.last_name,email:u.email,phone:u.phone,role:u.role});
app.get("/",(req,res)=>res.json({message:"API Job Board en fonctionnement."}));
app.post("/auth/register",async(req,res)=>{try{const{first_name,last_name,email,password,phone}=req.body;if(!first_name||!last_name||!email||!password)return res.status(400).json({error:"Prénom, nom, email et mot de passe obligatoires."});if(typeof password!=="string"||password.length<8)return res.status(400).json({error:"Le mot de passe doit contenir au moins 8 caractères."});const em=String(email).trim().toLowerCase(),[old]=await db.execute("SELECT id FROM people WHERE email=?",[em]);if(old.length)return res.status(409).json({error:"Email déjà utilisé."});const hash=await argon2.hash(password),[r]=await db.execute("INSERT INTO people(first_name,last_name,email,phone,password_hash,role) VALUES(?,?,?,?,?,'user')",[String(first_name).trim(),String(last_name).trim(),em,phone||null,hash]);const user={id:r.insertId,first_name:String(first_name).trim(),last_name:String(last_name).trim(),email:em,phone:phone||null,role:"user"};res.status(201).json({token:makeToken(user),user})}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur à l'inscription."})}});
app.post("/auth/login",async(req,res)=>{try{const{email,password}=req.body;if(!email||!password)return res.status(400).json({error:"Email et mot de passe obligatoires."});const[rows]=await db.execute("SELECT id,first_name,last_name,email,phone,password_hash,role FROM people WHERE email=?",[String(email).trim().toLowerCase()]);if(!rows.length||!await argon2.verify(rows[0].password_hash,password))return res.status(401).json({error:"Email ou mot de passe incorrect."});const user=safe(rows[0]);res.json({message:"Connexion réussie.",token:makeToken(user),user})}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur à la connexion."})}});
app.get("/auth/me",auth,async(req,res)=>{try{const[rows]=await db.execute("SELECT id,first_name,last_name,email,phone,role FROM people WHERE id=?",[req.user.id]);if(!rows.length)return res.status(404).json({error:"Compte introuvable."});res.json({user:rows[0]})}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur."})}});
app.put("/auth/me",auth,async(req,res)=>{try{const{first_name,last_name,phone}=req.body;if(!first_name||!last_name)return res.status(400).json({error:"Prénom et nom obligatoires."});await db.execute("UPDATE people SET first_name=?,last_name=?,phone=? WHERE id=?",[String(first_name).trim(),String(last_name).trim(),phone||null,req.user.id]);const[rows]=await db.execute("SELECT id,first_name,last_name,email,phone,role FROM people WHERE id=?",[req.user.id]);res.json({message:"Compte modifié.",user:rows[0]})}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur."})}});
app.get("/ads",async(req,res)=>{try{const[rows]=await db.execute(`SELECT a.id,a.title,a.short_description,a.full_description,a.salary_min,a.salary_max,a.location,a.contract_type,a.working_time,c.name AS company_name,cat.name AS category_name FROM ads a JOIN companies c ON c.id=a.company_id JOIN categories cat ON cat.id=a.category_id WHERE a.is_active=TRUE ORDER BY a.created_at DESC`);res.json(rows)}catch(e){console.error(e);res.status(500).json({error:"Impossible de charger les annonces."})}});
app.get("/ads/:id",async(req,res)=>{try{const[rows]=await db.execute(`SELECT a.id,a.title,a.short_description,a.full_description,a.salary_min,a.salary_max,a.location,a.contract_type,a.working_time,c.name AS company_name,cat.name AS category_name FROM ads a JOIN companies c ON c.id=a.company_id JOIN categories cat ON cat.id=a.category_id WHERE a.id=? AND a.is_active=TRUE`,[req.params.id]);if(!rows.length)return res.status(404).json({error:"Annonce introuvable."});res.json(rows[0])}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur."})}});
app.post("/ads/:id/applications",auth,async(req,res)=>{try{const{message}=req.body;if(!message||!String(message).trim())return res.status(400).json({error:"Message obligatoire."});const[ads]=await db.execute("SELECT id FROM ads WHERE id=? AND is_active=TRUE",[req.params.id]);if(!ads.length)return res.status(404).json({error:"Annonce introuvable."});const[old]=await db.execute("SELECT id FROM applications WHERE ad_id=? AND person_id=?",[req.params.id,req.user.id]);if(old.length)return res.status(409).json({error:"Déjà candidaté."});const[r]=await db.execute("INSERT INTO applications(ad_id,person_id,message) VALUES(?,?,?)",[req.params.id,req.user.id,String(message).trim()]);res.status(201).json({message:"Candidature envoyée.",applicationId:r.insertId})}catch(e){console.error(e);res.status(500).json({error:"Erreur candidature."})}});
const ar=express.Router();ar.use(auth,admin);
ar.get("/ads",async(req,res)=>{try{const[rows]=await db.execute("SELECT id,title,short_description,full_description,salary_min,salary_max,location,contract_type,working_time,is_active,company_id,category_id FROM ads ORDER BY id DESC");res.json(rows)}catch(e){res.status(500).json({error:"Erreur serveur."})}});
ar.post("/ads",async(req,res)=>{try{const{title,short_description,full_description,salary_min,salary_max,location,contract_type,working_time,company_id,category_id}=req.body;const contracts=["CDI","CDD","internship","apprenticeship","freelance"],times=["full_time","part_time"];if(!title||!short_description||!full_description||!contracts.includes(contract_type)||!company_id||!category_id)return res.status(400).json({error:"Champs requis manquants ou contrat invalide."});const time=working_time||"full_time";if(!times.includes(time))return res.status(400).json({error:"Temps de travail invalide."});const[r]=await db.execute("INSERT INTO ads(title,short_description,full_description,salary_min,salary_max,location,contract_type,working_time,company_id,category_id) VALUES(?,?,?,?,?,?,?,?,?,?)",[title,short_description,full_description,salary_min??null,salary_max??null,location||null,contract_type,time,company_id,category_id]);res.status(201).json({message:"Annonce créée.",id:r.insertId})}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur : vérifier société et catégorie."})}});
ar.put("/ads/:id",async(req,res)=>{try{const{title,short_description,full_description,salary_min,salary_max,location,contract_type,working_time,company_id,category_id,is_active}=req.body;if(!title||!short_description||!full_description||!company_id||!category_id)return res.status(400).json({error:"Champs requis manquants."});const[r]=await db.execute("UPDATE ads SET title=?,short_description=?,full_description=?,salary_min=?,salary_max=?,location=?,contract_type=?,working_time=?,company_id=?,category_id=?,is_active=? WHERE id=?",[title,short_description,full_description,salary_min??null,salary_max??null,location||null,contract_type,working_time||"full_time",company_id,category_id,is_active===false?0:1,req.params.id]);if(!r.affectedRows)return res.status(404).json({error:"Annonce introuvable."});res.json({message:"Annonce modifiée."})}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur."})}});
ar.delete("/ads/:id",async(req,res)=>{try{const[r]=await db.execute("DELETE FROM ads WHERE id=?",[req.params.id]);if(!r.affectedRows)return res.status(404).json({error:"Annonce introuvable."});res.json({message:"Annonce supprimée."})}catch(e){console.error(e);res.status(500).json({error:"Erreur serveur."})}});
ar.get("/applications",async(req,res)=>{try{const[rows]=await db.execute(`SELECT ap.id,ap.ad_id,ap.message,ap.applied_at,ap.status,p.first_name,p.last_name,p.email,p.phone,a.title AS ad_title FROM applications ap JOIN people p ON p.id=ap.person_id JOIN ads a ON a.id=ap.ad_id ORDER BY ap.applied_at DESC`);res.json(rows)}catch(e){res.status(500).json({error:"Erreur serveur."})}});
app.use("/admin",ar);app.use((req,res)=>res.status(404).json({error:"Route introuvable."}));
(async()=>{try{await db.query("SELECT 1");app.listen(PORT,()=>console.log(`API prête sur http://localhost:${PORT}`))}catch(e){console.error("Connexion MySQL impossible:",e.message);process.exit(1)}})();
